[package]
name = "rumi"
version = "0.1.0"
edition = "2021"
authors = ["cseryou"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termcolor = "1.1.2"
colored = "2.0.4"
clap = { version = "4.3.11", features = ["derive"] }
